#!/bin/sh -eu

newletter() {
  letter_name=$1
  to_folder="$(date "+%Y-%m-%d")_$letter_name"
  git clone -q --depth 1 git@github.com:jfornoff/letter_template.git $to_folder
  cd $to_folder && rm -rf .git
}
