#!/bin/sh -eu

function newinvoice() {
  invoice_name=$1
  to_folder="$(date "+%Y-%m-%d")_$invoice_name"
  git clone -q --depth 1 git@github.com:jfornoff/invoice.git $to_folder
  cd $to_folder && rm -rf .git
}
